# Site
repository: mharikmert/mharikmert.github.io
favicon: /images/favicon.ico
# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

# Content configuration version
version: 2

# Personal info
name: Mahmut Hilmi Arıkmert
title: Software Developer
email: contact@mharikmert.dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mharikmert
github_username: mharikmert
linkedin_username: mharikmert
hackerrank_username: mharikmert
blog: blog.mharikmert.dev
# About Section
about_title: About
about_profile_image: images/profile.jpg
about_content: |
  Loves to build, operate and automate things. A Firm believer in the power of knowledge, driven by a passion for all aspects of the software development lifecycle and dedicated to continuously learning and growing. 
  Proactive problem solver, knowledge worker, and software developer in the early stage of his career.
more_title: A Little More About Me
more_content: |
  Alongside my interests in software engineering some of my other interests and hobbies are:
  * Playing/Watching Basketball and Tennis
  * Reading Classical Novels
  * Researching about Space and Universe
  * Math & Geometry

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
