# Site
repository: mharikmert/mharikmert.github.io
favicon: /images/favicon.ico
# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

# Content configuration version
version: 2

# Personal info
name: Mahmut Hilmi Arıkmert
title: Software Developer
email: contact@mharikmert.dev
# resume: /resume/resume.pdf
# resume_title: Curriculum Vitae

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: iamhillme
github_username: mharikmert
linkedin_username: mharikmert
hackerrank_username: mharikmert
blog: blog.mharikmert.dev
# About Section
about_title: About
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A knowledge worker and a software developer interested in all the aspects of software development. 
  Enjoys being challenged and engaging with projects that require working outside of comfort zone and knowledge set. Besides, Software Developer at <a target = "_blank" href = "https://www.renault.com.tr"> Renault Turkey. </a>

more_title: A Little More About Me
more_content: |
  Alongside my interests in software engineering some of my other interests and hobbies are:
  * Playing/Watching Basketball and Tennis
  * Reading Classical Novels
  * Researching about Space and Universe
  * Math & Geometry

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
